---
# tasks file for hello_motd
- name: Generate greeting and store result
  example.demo.demo_hello:
    name: "{{ motd_hello_friend_name }}"
  register: demo_greeting

- name: Store test in /etc/motd
  ansible.builtin.copy:
    content: "{{ demo_greeting.fact }}\n"
    dest: /etc/motd
    mode: "0644"
  become: true
...
