---
- name: Set MOTD
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Invoke hello_motd role
      ansible.builtin.include_role:
        name: example.demo.hello_motd
      vars:
        friend_name: "GitHub Action"
